### ISSUE TITLE
consul api?

### ISSUE THREAD

**Issue by aaronhurt** [Pravoru/consulbeat#1]
Have you thought about using the official Consul API to query the nodes?

https://github.com/hashicorp/consul/tree/master/api

https://godoc.org/github.com/hashicorp/consul/api

**Comment by Elufimov** [comment]
Hi! Do you mean this api https://www.consul.io/docs/agent/http/catalog.html#catalog_nodes ?

**Comment by aaronhurt** [comment]
I was talking about the golang SDK that hashicorp provides as part of the consul repo ... you can find it at the links above.  It uses the same HTTP API you referenced but handles the HTTP client and all of the marshal/unmarshal for you and defines structs for all of the returned payloads.

**Comment by Elufimov** [comment]
I thought you was talking about adding a new data that will be pulled from consul. About migration to official api, yes I have some plans. But I do not know when I can implement it.

**Comment by aaronhurt** [comment]
Would you accept a pull request?  I was interested in adding a few other features including telemetry data.

**Comment by Elufimov** [comment]
Yes, we would be happy to see the pull requests. I close this issue than.
